"""
similarity_score_analytics.py
-----------------------------
Reusable Streamlit component for similarity score distribution analytics.
Visualizes and analyzes similarity scores generated by the plagiarism detection system.
"""

from __future__ import annotations

import json
import logging
from typing import Any, Dict, List
import numpy as np
import pandas as pd
import plotly.graph_objects as go
import streamlit as st

# Setup logging
logger = logging.getLogger(__name__)


# ── CACHED DATA LOADING ───────────────────────────────────────────────────────

@st.cache_data(ttl=60)
def _load_incidents_data() -> List[Any]:
    """Fetch all plagiarism incidents from the database, cached for performance."""
    try:
        from src.db.incidents import get_all_incidents
        # Retrieve incidents with a sufficiently large limit
        return get_all_incidents(limit=100000)
    except Exception as e:
        logger.error("Failed to load incidents for similarity score analytics: %s", e)
        return []


# ── HELPER FUNCTIONS ──────────────────────────────────────────────────────────

def _safe_float(value: Any, default: float = 0.0) -> float:
    """Safely convert a value to float, handling exceptions."""
    if value is None:
        return default
    try:
        return float(value)
    except (ValueError, TypeError):
        return default


def _safe_int(value: Any, default: int = 0) -> int:
    """Safely convert a value to int, handling exceptions."""
    if value is None:
        return default
    try:
        return int(value)
    except (ValueError, TypeError):
        return default


def _compute_statistics(scores: pd.Series) -> Dict[str, float | int]:
    """Compute statistical metrics for the similarity scores."""
    if scores.empty:
        return {
            "total_samples": 0,
            "mean": 0.0,
            "median": 0.0,
            "std_dev": 0.0,
            "variance": 0.0,
            "min_val": 0.0,
            "max_val": 0.0,
            "range_val": 0.0,
        }

    total = len(scores)
    mean_val = float(scores.mean())
    median_val = float(scores.median())
    std_val = float(scores.std()) if total > 1 else 0.0
    var_val = float(scores.var()) if total > 1 else 0.0
    min_val = float(scores.min())
    max_val = float(scores.max())
    range_val = max_val - min_val

    return {
        "total_samples": total,
        "mean": mean_val,
        "median": median_val,
        "std_dev": std_val,
        "variance": var_val,
        "min_val": min_val,
        "max_val": max_val,
        "range_val": range_val,
    }


def _compute_percentiles(scores: pd.Series) -> Dict[str, float]:
    """Compute percentile values for the similarity scores."""
    if scores.empty:
        return {
            "P25": 0.0,
            "P50": 0.0,
            "P75": 0.0,
            "P90": 0.0,
            "P95": 0.0,
            "P99": 0.0,
        }

    # Calculate percentiles using numpy
    p_values = np.percentile(scores, [25, 50, 75, 90, 95, 99])
    return {
        "P25": float(p_values[0]),
        "P50": float(p_values[1]),
        "P75": float(p_values[2]),
        "P90": float(p_values[3]),
        "P95": float(p_values[4]),
        "P99": float(p_values[5]),
    }


def _detect_outliers(scores: pd.Series) -> Dict[str, Any]:
    """Detect outliers in the scores using the Interquartile Range (IQR) method."""
    if scores.empty or len(scores) < 4:
        return {
            "total_outliers": 0,
            "highest_outlier": 0.0,
            "lowest_outlier": 0.0,
            "outlier_percentage": 0.0,
            "q1": 0.0,
            "q3": 0.0,
            "iqr": 0.0,
            "lower_bound": 0.0,
            "upper_bound": 0.0,
        }

    q1 = float(scores.quantile(0.25))
    q3 = float(scores.quantile(0.75))
    iqr = q3 - q1
    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    outliers = scores[(scores < lower_bound) | (scores > upper_bound)]
    total_outliers = len(outliers)
    outlier_pct = (total_outliers / len(scores)) * 100.0

    highest_outlier = float(outliers.max()) if total_outliers > 0 else 0.0
    lowest_outlier = float(outliers.min()) if total_outliers > 0 else 0.0

    return {
        "total_outliers": total_outliers,
        "highest_outlier": highest_outlier,
        "lowest_outlier": lowest_outlier,
        "outlier_percentage": outlier_pct,
        "q1": q1,
        "q3": q3,
        "iqr": iqr,
        "lower_bound": lower_bound,
        "upper_bound": upper_bound,
    }


def _prepare_dataframe(incidents: List[Any]) -> pd.DataFrame:
    """Convert raw incidents list into a clean Pandas DataFrame with similarity scores."""
    if not incidents:
        return pd.DataFrame(columns=["similarity_score"])

    rows = []
    for inc in incidents:
        is_dict = isinstance(inc, dict)

        def _get_val(key: str, default: Any = None) -> Any:
            if is_dict:
                return inc.get(key, default)
            try:
                return getattr(inc, key, default)
            except AttributeError:
                return default

        # Support both 'similarity_score' and property 'similarity'
        score = _get_val("similarity_score")
        if score is None:
            score = _get_val("similarity")

        rows.append({
            "similarity_score": _safe_float(score, default=0.0)
        })

    return pd.DataFrame(rows)


def _render_metric_card(
    label: str,
    value: str | int | float,
    icon: str,
    description: str,
    accent_color_var: str
) -> None:
    """Render a styled KPI metric card using custom HTML/CSS."""
    card_html = f"""
    <div class="kpi-card" style="border-bottom-color: var({accent_color_var});">
        <div class="kpi-card-header">
            <span class="kpi-card-title">{label}</span>
            <span class="kpi-card-icon">{icon}</span>
        </div>
        <div class="kpi-card-value">{value}</div>
        <div class="kpi-card-desc">{description}</div>
    </div>
    """
    st.markdown(card_html, unsafe_allow_html=True)


def _apply_plotly_theme(fig: go.Figure, title: str, theme_colors: Dict[str, str], margin_left: int = 50) -> None:
    """Style Plotly figures layout to match active light or dark themes."""
    fig.update_layout(
        title=dict(
            text=title,
            font=dict(
                family="'Inter', sans-serif",
                size=16,
                color=theme_colors.get("ink", "#0F172A")
            ),
            x=0.02
        ),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(
            family="'Inter', sans-serif",
            color=theme_colors.get("ink", "#0F172A")
        ),
        margin=dict(l=margin_left, r=30, t=60, b=40),
        legend=dict(
            font=dict(color=theme_colors.get("muted", "#64748B")),
            bgcolor="rgba(0,0,0,0)"
        ),
        xaxis=dict(
            gridcolor=theme_colors.get("border", "#E2E8F0"),
            tickfont=dict(color=theme_colors.get("muted", "#64748B")),
            titlefont=dict(color=theme_colors.get("ink", "#0F172A"))
        ),
        yaxis=dict(
            gridcolor=theme_colors.get("border", "#E2E8F0"),
            tickfont=dict(color=theme_colors.get("muted", "#64748B")),
            titlefont=dict(color=theme_colors.get("ink", "#0F172A"))
        )
    )


def _render_histogram(
    scores: pd.Series,
    bins: int,
    show_density: bool,
    show_mean_line: bool
) -> None:
    """Render an interactive Plotly histogram."""
    try:
        from app.theme import get_chart_colors
        colors = get_chart_colors()
    except Exception:
        colors = {}

    fig = go.Figure()
    histnorm = "probability density" if show_density else None
    y_title = "Density" if show_density else "Count"

    fig.add_trace(
        go.Histogram(
            x=scores,
            nbinsx=bins,
            histnorm=histnorm,
            name="Similarity Scores",
            marker=dict(
                color=colors.get("accent", "#0D9488"),
                line=dict(
                    color=colors.get("card", "#FFFFFF"),
                    width=1
                )
            ),
            hovertemplate="Score Range: %{x}<br>" + f"{y_title}: %{{y}}<extra></extra>"
        )
    )

    if show_mean_line:
        mean_val = float(scores.mean())
        fig.add_vline(
            x=mean_val,
            line_dash="dash",
            line_color=colors.get("danger", "#FF4B4B"),
            annotation_text=f"Mean: {mean_val:.4f}",
            annotation_position="top right",
            annotation_font=dict(color=colors.get("danger", "#FF4B4B"))
        )

    _apply_plotly_theme(
        fig,
        title="Similarity Score Distribution Histogram",
        theme_colors=colors
    )

    fig.update_layout(
        xaxis_title="Similarity Score",
        yaxis_title=y_title,
        bargap=0.05
    )

    st.plotly_chart(fig, use_container_width=True)


def _render_boxplot(scores: pd.Series) -> None:
    """Render an interactive Plotly box plot."""
    try:
        from app.theme import get_chart_colors
        colors = get_chart_colors()
    except Exception:
        colors = {}

    fig = go.Figure()
    fig.add_trace(
        go.Box(
            y=scores,
            name="Similarity Score",
            marker_color=colors.get("accent", "#0D9488"),
            boxpoints="outliers",
            hovertemplate="Value: %{y}<extra></extra>"
        )
    )

    _apply_plotly_theme(
        fig,
        title="Similarity Score Box Plot",
        theme_colors=colors
    )

    fig.update_layout(
        yaxis_title="Similarity Score",
        xaxis=dict(showticklabels=False)
    )

    st.plotly_chart(fig, use_container_width=True)


def _render_percentile_table(percentiles: Dict[str, float]) -> None:
    """Render a styled Streamlit table showing percentiles."""
    df = pd.DataFrame([
        {
            "Percentile": k,
            "Similarity Score": f"{v:.4f}",
            "Percentage Equivalent": f"{v * 100.0:.2f}%"
        }
        for k, v in percentiles.items()
    ])
    st.table(df)


def _render_outlier_summary(outliers_info: Dict[str, Any]) -> None:
    """Render the outlier analysis summary metrics."""
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        _render_metric_card(
            label="Total Outliers",
            value=f"{outliers_info['total_outliers']}",
            icon="🚨",
            description="Number of detected outliers",
            accent_color_var="--danger"
        )
    with col2:
        _render_metric_card(
            label="Outlier Percentage",
            value=f"{outliers_info['outlier_percentage']:.2f}%",
            icon="📊",
            description="Percentage of all samples",
            accent_color_var="--danger"
        )
    with col3:
        _render_metric_card(
            label="Highest Outlier",
            value=f"{outliers_info['highest_outlier']:.4f}",
            icon="⬆️",
            description="Maximum outlier value",
            accent_color_var="--accent"
        )
    with col4:
        _render_metric_card(
            label="Lowest Outlier",
            value=f"{outliers_info['lowest_outlier']:.4f}",
            icon="⬇️",
            description="Minimum outlier value",
            accent_color_var="--accent"
        )


def _render_download_buttons(stats: Dict[str, Any], percentiles: Dict[str, float]) -> None:
    """Render download buttons for statistics and percentiles."""
    # Prepare statistics data
    stats_df = pd.DataFrame([{"Metric": k, "Value": v} for k, v in stats.items()])
    stats_csv = stats_df.to_csv(index=False).encode('utf-8')
    stats_json = json.dumps(stats, indent=4).encode('utf-8')

    # Prepare percentile data
    pct_df = pd.DataFrame([{"Percentile": k, "Value": v} for k, v in percentiles.items()])
    pct_csv = pct_df.to_csv(index=False).encode('utf-8')

    col1, col2, col3 = st.columns(3)
    with col1:
        st.download_button(
            label="📥 Download Statistics (CSV)",
            data=stats_csv,
            file_name="similarity_statistics.csv",
            mime="text/csv",
            use_container_width=True
        )
    with col2:
        st.download_button(
            label="📥 Download Statistics (JSON)",
            data=stats_json,
            file_name="similarity_statistics.json",
            mime="application/json",
            use_container_width=True
        )
    with col3:
        st.download_button(
            label="📥 Download Percentiles (CSV)",
            data=pct_csv,
            file_name="similarity_percentiles.csv",
            mime="text/csv",
            use_container_width=True
        )


# ── MAIN COMPONENT ENTRYPOINT ─────────────────────────────────────────────────

def render_similarity_score_analytics() -> None:
    """Entrypoint function to render the similarity score distribution analytics page."""
    # Inject CSS for consistent styling
    css = """
    <style>
    .analytics-header {
        margin-bottom: 25px;
        border-bottom: 2px solid var(--border-color, #E2E8F0);
        padding-bottom: 15px;
    }
    .analytics-title {
        font-size: 2.25rem;
        font-weight: 800;
        color: var(--text-color, #0F172A);
        margin: 0 0 8px 0;
        letter-spacing: -0.025em;
    }
    .analytics-subtitle {
        font-size: 1.05rem;
        color: var(--secondary-text-color, #64748B);
        margin: 0;
    }
    .kpi-card {
        background-color: var(--card, #FFFFFF);
        border: 1px solid var(--border-color, #E2E8F0);
        border-bottom: 4px solid var(--accent-color, #0D9488);
        border-radius: 12px;
        padding: 20px;
        margin-bottom: 15px;
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.02);
        transition: transform 0.25s ease-in-out, box-shadow 0.25s ease-in-out;
        display: flex;
        flex-direction: column;
        min-height: 140px;
    }
    .kpi-card:hover {
        transform: translateY(-5px);
        box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
    }
    .kpi-card-header {
        display: flex;
        justify-content: space-between;
        align-items: center;
        margin-bottom: 10px;
    }
    .kpi-card-title {
        font-size: 0.8rem;
        font-weight: 600;
        color: var(--secondary-text-color, #64748B);
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }
    .kpi-card-icon {
        font-size: 1.4rem;
    }
    .kpi-card-value {
        font-size: 2.2rem;
        font-weight: 700;
        color: var(--text-color, #0F172A);
        line-height: 1.2;
    }
    .kpi-card-desc {
        font-size: 0.75rem;
        color: var(--secondary-text-color, #64748B);
        margin-top: 5px;
    }
    .empty-state {
        text-align: center;
        padding: 50px 20px;
        border: 1px dashed var(--border-color, #E2E8F0);
        border-radius: 12px;
        background-color: var(--secondary-bg, #F8FAFC);
        margin: 20px 0;
    }
    .empty-icon {
        font-size: 3.5rem;
        margin-bottom: 12px;
    }
    .empty-title {
        font-size: 1.35rem;
        font-weight: 700;
        color: var(--text-color, #0F172A);
        margin-bottom: 8px;
    }
    .empty-desc {
        font-size: 0.95rem;
        color: var(--secondary-text-color, #64748B);
        max-width: 500px;
        margin: 0 auto;
    }
    </style>
    """
    st.markdown(css, unsafe_allow_html=True)

    # SECTION 1: Dashboard Header
    st.markdown(
        """
        <div class="analytics-header">
            <h1 class="analytics-title">Similarity Score Distribution Analytics</h1>
            <p class="analytics-subtitle">Analyze the statistical distribution of plagiarism similarity scores.</p>
        </div>
        """,
        unsafe_allow_html=True
    )

    try:
        raw_incidents = _load_incidents_data()
    except Exception as e:
        logger.error("Error loading similarity analytics data: %s", e)
        raw_incidents = []

    df = _prepare_dataframe(raw_incidents)

    # SECTION 9: Empty State
    if df.empty or "similarity_score" not in df.columns or len(df["similarity_score"]) == 0:
        st.markdown(
            """
            <div class="empty-state">
                <div class="empty-icon">📊</div>
                <div class="empty-title">No similarity data available.</div>
                <div class="empty-desc">Upload documents to begin analysis.</div>
            </div>
            """,
            unsafe_allow_html=True
        )
        return

    scores = df["similarity_score"].astype(float)

    # SECTION 2: Statistics Cards
    st.markdown("### Key Performance Indicators")
    stats = _compute_statistics(scores)

    # Row 1
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        _render_metric_card(
            label="Total Samples",
            value=f"{stats['total_samples']}",
            icon="🔢",
            description="Total count of similarity scores",
            accent_color_var="--accent"
        )
    with col2:
        _render_metric_card(
            label="Mean Similarity",
            value=f"{stats['mean']:.4f}",
            icon="⚖️",
            description="Average similarity score",
            accent_color_var="--accent"
        )
    with col3:
        _render_metric_card(
            label="Median Similarity",
            value=f"{stats['median']:.4f}",
            icon="🎯",
            description="Middle similarity score",
            accent_color_var="--accent"
        )
    with col4:
        _render_metric_card(
            label="Std Deviation",
            value=f"{stats['std_dev']:.4f}",
            icon="📐",
            description="Standard deviation of scores",
            accent_color_var="--accent"
        )

    # Row 2
    col5, col6, col7, col8 = st.columns(4)
    with col5:
        _render_metric_card(
            label="Variance",
            value=f"{stats['variance']:.4f}",
            icon="📊",
            description="Variance of similarity scores",
            accent_color_var="--accent"
        )
    with col6:
        _render_metric_card(
            label="Minimum",
            value=f"{stats['min_val']:.4f}",
            icon="⬇️",
            description="Lowest similarity score recorded",
            accent_color_var="--accent"
        )
    with col7:
        _render_metric_card(
            label="Maximum",
            value=f"{stats['max_val']:.4f}",
            icon="⬆️",
            description="Highest similarity score recorded",
            accent_color_var="--accent"
        )
    with col8:
        _render_metric_card(
            label="Range",
            value=f"{stats['range_val']:.4f}",
            icon="↔️",
            description="Difference between Max and Min",
            accent_color_var="--accent"
        )

    st.markdown("---")

    # SECTION 3: Histogram & SECTION 4: Box Plot
    chart_tab1, chart_tab2 = st.tabs(["📊 Histogram", "📦 Box Plot"])
    with chart_tab1:
        c1, c2, c3 = st.columns([2, 1, 1])
        with c1:
            bins = st.slider("Number of Bins", min_value=5, max_value=100, value=20, step=1, key="hist_bins")
        with c2:
            show_density = st.checkbox("Show Density", value=False, key="hist_density", help="Show probability density instead of count.")
        with c3:
            show_mean = st.checkbox("Show Mean Line", value=True, key="hist_mean", help="Show vertical line representing the mean score.")

        _render_histogram(scores, bins, show_density, show_mean)

    with chart_tab2:
        _render_boxplot(scores)

    st.markdown("---")

    # SECTION 5: Percentile Analysis
    st.markdown("### Percentile Analysis")
    percentiles = _compute_percentiles(scores)
    _render_percentile_table(percentiles)

    st.markdown("---")

    # SECTION 6: Outlier Analysis
    st.markdown("### Outlier Analysis (IQR Method)")
    outliers_info = _detect_outliers(scores)
    _render_outlier_summary(outliers_info)

    st.markdown(
        f"""
        <div style="font-size: 0.85rem; color: var(--secondary-text-color, #64748B); margin-top: 10px; margin-bottom: 20px;">
            ℹ️ Outlier detection is based on the Interquartile Range (IQR).
            <b>Q1</b> = {outliers_info['q1']:.4f}, <b>Q3</b> = {outliers_info['q3']:.4f}, <b>IQR</b> = {outliers_info['iqr']:.4f}.<br>
            Thresholds: Lower bound = {outliers_info['lower_bound']:.4f}, Upper bound = {outliers_info['upper_bound']:.4f}.
        </div>
        """,
        unsafe_allow_html=True
    )

    st.markdown("---")

    # SECTION 7: Distribution Summary
    st.markdown("### Distribution Summary & Interpretation")

    mean_val = stats["mean"]
    median_val = stats["median"]
    diff_val = mean_val - median_val
    skew_val = float(scores.skew()) if len(scores) > 2 else 0.0
    std_val = stats["std_dev"]
    q1 = outliers_info["q1"]
    q3 = outliers_info["q3"]

    col_s1, col_s2, col_s3 = st.columns(3)
    col_s1.metric("Mean - Median Difference", f"{diff_val:.4f}")
    col_s2.metric("Distribution Skewness", f"{skew_val:.4f}")
    col_s3.metric("Standard Deviation", f"{std_val:.4f}")

    # Skewness interpretation
    if skew_val > 0.5:
        skew_desc = f"right-skewed (skewness = {skew_val:.2f}), suggesting a concentration of lower similarity scores with a trailing tail of high-similarity cases."
    elif skew_val < -0.5:
        skew_desc = f"left-skewed (skewness = {skew_val:.2f}), indicating a concentration of high-similarity scores with a trailing tail of lower scores."
    else:
        skew_desc = f"relatively symmetric (skewness = {skew_val:.2f}), indicating a balanced distribution of similarity scores around the center."

    # Concentration interpretation
    interpretation_text = f"Scores are concentrated between {q1:.2f} and {q3:.2f} indicating consistent semantic similarity."

    # Spread interpretation
    if std_val < 0.1:
        spread_desc = "The low standard deviation indicates that the similarity scores are tightly grouped around the mean, representing high consistency in matching patterns."
    else:
        spread_desc = "The standard deviation represents a wider dispersion of scores, indicating a diverse range of plagiarism severities across the incident reports."

    summary_text = (
        f"The similarity score distribution exhibits a mean of **{mean_val:.4f}** and a median of **{median_val:.4f}** "
        f"(with a difference of **{diff_val:.4f}**). The overall distribution is {skew_desc} "
        f"**{interpretation_text}** {spread_desc}"
    )

    st.info(summary_text)

    st.markdown("---")

    # SECTION 8: Downloads
    st.markdown("### Export Analytics Data")
    _render_download_buttons(stats, percentiles)
