"""
tests/e2e/fixtures/sample_docs.py
----------------------------------
Programmatic generators for the dummy assignment files used by the
Playwright E2E test (Issue #3030).

Two near-duplicate documents + one unrelated document.
"""

from __future__ import annotations

from pathlib import Path

STUDENT_A_TEXT = (
    "Photosynthesis is the process by which green plants, algae, and some "
    "bacteria convert light energy into chemical energy stored in glucose. "
    "The reaction takes place in the chloroplasts, which contain the green "
    "pigment chlorophyll. During photosynthesis, carbon dioxide from the "
    "atmosphere and water absorbed by the roots are transformed into glucose "
    "and oxygen, with sunlight providing the energy required to drive the "
    "reaction. This process is fundamental to life on Earth because it is "
    "the primary source of the oxygen we breathe and the base of nearly "
    "every food chain."
)

STUDENT_B_TEXT = (
    # Same semantic content, lexical substitutions throughout.
    "Photosynthesis refers to the mechanism through which green flora, "
    "seaweed, and certain microorganisms translate light energy into "
    "chemical energy held within glucose molecules. The process occurs "
    "inside the chloroplasts, which hold the green pigment chlorophyll. "
    "In photosynthesis, atmospheric carbon dioxide together with water "
    "drawn up by the root system are converted into glucose and oxygen, "
    "with sunlight supplying the energy needed to power the reaction. "
    "This process is essential to life on our planet because it forms "
    "the primary source of the oxygen we inhale and the foundation of "
    "almost every food web."
)

STUDENT_C_TEXT = (
    # Unrelated content for negative-test coverage.
    "The waterfall cascaded down the granite cliff, sending a cold mist "
    "across the moss-covered boulders below. A lone eagle circled "
    "overhead, riding the updrafts generated by the warm afternoon sun. "
    "The forest was otherwise silent, save for the distant call of a "
    "thrush and the persistent rumble of the river carving its way "
    "through the canyon."
)


def write_sample_docs(target_dir: Path) -> dict[str, Path]:
    """Write the three sample .txt files into ``target_dir``."""
    target_dir.mkdir(parents=True, exist_ok=True)
    paths: dict[str, Path] = {}
    for name, content in (
        ("student_a.txt", STUDENT_A_TEXT),
        ("student_b.txt", STUDENT_B_TEXT),
        ("student_c.txt", STUDENT_C_TEXT),
    ):
        p = target_dir / name
        p.write_text(content, encoding="utf-8")
        paths[name] = p
    return paths
