# MIT License
#
# Copyright (c) 2026 Ganesh Kambli
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""
src/utils/diff_renderer.py
--------------------------
HTML/CSS rendering utilities for semantic sequence alignment diffs.

Converts the alignment map generated by semantic_alignment.py into a
responsive, interactive HTML side-by-side diff view. Supports both
Light and Dark themes to integrate seamlessly with the Streamlit UI.

Recent Additions (Issue #1957):
- Added render_semantic_diff_html() to generate GitHub-style diff payloads.
- Added CSS variables for dynamic theme switching.
"""

import html
import logging
from typing import Any, Dict, List

logger = logging.getLogger(__name__)

# CSS Templates for Light and Dark modes
_CSS_LIGHT = """
<style>
    .diff-container {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
        font-size: 14px;
        line-height: 1.6;
        color: #24292e;
        background-color: #ffffff;
        border: 1px solid #e1e4e8;
        border-radius: 6px;
        overflow-x: auto;
    }
    .diff-row {
        display: flex;
        border-bottom: 1px solid #e1e4e8;
    }
    .diff-row:last-child { border-bottom: none; }
    .diff-col {
        flex: 1;
        padding: 8px 12px;
        min-width: 0;
        word-wrap: break-word;
    }
    .diff-col:first-child { border-right: 1px solid #e1e4e8; }
    .diff-type {
        display: inline-block;
        font-size: 11px;
        font-weight: 600;
        padding: 2px 6px;
        border-radius: 3px;
        margin-bottom: 4px;
        text-transform: uppercase;
    }
    .type-match { background-color: #dcffe4; color: #22863a; }
    .type-paraphrase { background-color: #fff5b1; color: #b08800; }
    .type-insert_a { background-color: #ffdce0; color: #cb2431; }
    .type-insert_b { background-color: #dbedff; color: #0366d6; }
    .score-badge {
        float: right;
        font-size: 11px;
        color: #586069;
        background: #f6f8fa;
        padding: 2px 6px;
        border-radius: 3px;
    }
    .text-content { margin-top: 4px; white-space: pre-wrap; }
</style>
"""

_CSS_DARK = """
<style>
    .diff-container {
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
        font-size: 14px;
        line-height: 1.6;
        color: #c9d1d9;
        background-color: #0d1117;
        border: 1px solid #30363d;
        border-radius: 6px;
        overflow-x: auto;
    }
    .diff-row {
        display: flex;
        border-bottom: 1px solid #21262d;
    }
    .diff-row:last-child { border-bottom: none; }
    .diff-col {
        flex: 1;
        padding: 8px 12px;
        min-width: 0;
        word-wrap: break-word;
    }
    .diff-col:first-child { border-right: 1px solid #21262d; }
    .diff-type {
        display: inline-block;
        font-size: 11px;
        font-weight: 600;
        padding: 2px 6px;
        border-radius: 3px;
        margin-bottom: 4px;
        text-transform: uppercase;
    }
    .type-match { background-color: #144d29; color: #56d364; }
    .type-paraphrase { background-color: #4d3800; color: #e3b341; }
    .type-insert_a { background-color: #67060c; color: #f85149; }
    .type-insert_b { background-color: #051d4d; color: #58a6ff; }
    .score-badge {
        float: right;
        font-size: 11px;
        color: #8b949e;
        background: #161b22;
        padding: 2px 6px;
        border-radius: 3px;
    }
    .text-content { margin-top: 4px; white-space: pre-wrap; }
</style>
"""


def render_semantic_diff_html(
    alignment_map: list[dict[str, Any]],
    theme: str = "light",
) -> str:
    """Convert a semantic alignment map into a responsive HTML/CSS diff string.

    Generates a GitHub-style side-by-side diff view. Semantic additions are
    highlighted in blue, deletions in red, exact matches in green, and
    paraphrased modifications in yellow. Hovering over a row displays the
    exact cosine similarity score.

    Args:
        alignment_map: List of alignment operations from align_semantic_sequences().
        theme: "light" or "dark" to match the Streamlit application theme.

    Returns:
        A complete HTML string ready to be injected via streamlit.components.v1.html.
    """
    if not alignment_map:
        return "<p style='color: #666;'>No alignment data available.</p>"

    css = _CSS_DARK if theme.lower() == "dark" else _CSS_LIGHT

    html_parts = [css, '<div class="diff-container">']

    # Header row
    html_parts.append(
        """
        <div class="diff-row" style="background-color: rgba(0,0,0,0.05); font-weight: bold;">
            <div class="diff-col">Document A (Source)</div>
            <div class="diff-col">Document B (Suspicious)</div>
        </div>
    """
    )

    for op in alignment_map:
        op_type = op.get("type", "match")
        text_a = op.get("text_a") or ""
        text_b = op.get("text_b") or ""
        score = op.get("score", 0.0)

        # Escape HTML entities to prevent XSS and rendering issues
        safe_a = html.escape(text_a)
        safe_b = html.escape(text_b)

        # Determine label and CSS class
        if op_type == "match":
            label = "Exact Match"
            css_class = "type-match"
        elif op_type == "paraphrase":
            label = "Paraphrase"
            css_class = "type-paraphrase"
        elif op_type == "insert_a":
            label = "Deletion (Only in A)"
            css_class = "type-insert_a"
            safe_b = "<em style='opacity: 0.5;'>[No corresponding text]</em>"
        elif op_type == "insert_b":
            label = "Addition (Only in B)"
            css_class = "type-insert_b"
            safe_a = "<em style='opacity: 0.5;'>[No corresponding text]</em>"
        else:
            label = "Unknown"
            css_class = ""

        score_str = f"{score:.2f}" if score > 0 else "N/A"

        row_html = f"""
        <div class="diff-row">
            <div class="diff-col">
                <span class="diff-type {css_class}">{label}</span>
                <span class="score-badge" title="Cosine Similarity Score">Sim: {score_str}</span>
                <div class="text-content">{safe_a}</div>
            </div>
            <div class="diff-col">
                <span class="diff-type {css_class}">{label}</span>
                <span class="score-badge" title="Cosine Similarity Score">Sim: {score_str}</span>
                <div class="text-content">{safe_b}</div>
            </div>
        </div>
        """
        html_parts.append(row_html)

    html_parts.append("</div>")

    return "".join(html_parts)
