"""
src/core/edit_history_analyzer.py
---------------------------------
Edit History and Provenance Anomaly Analyzer.

Computes edit velocity, author mismatch scores, and template similarity
to flag suspicious document provenance (e.g., purchased essays with
impossible editing times or mismatched author tags).
"""

import logging
from typing import Dict, Any, Optional
from datetime import datetime, timedelta

from src.security.metadata_forensics import (
    extract_docx_metadata,
    extract_pdf_metadata,
    parse_pdf_date,
)

logger = logging.getLogger(__name__)

# Thresholds for anomaly detection
MIN_EDITING_MINUTES_PER_PAGE = 2.0  # Less than 2 mins/page is suspicious
MAX_EDITING_MINUTES_PER_PAGE = (
    120.0  # More than 2 hours/page might be suspicious (or just normal)
)
AUTHOR_MISMATCH_PENALTY = 0.8  # High penalty if Creator != LastModifiedBy


def analyze_edit_velocity(
    total_editing_time_minutes: Optional[float], page_count: int
) -> Dict[str, Any]:
    """Analyze the editing velocity of a document.

    Computes the minutes spent editing per page. Extremely low values
    (e.g., a 20-page paper edited for 4 minutes total) strongly indicate
    the document was purchased, copied, or generated by AI without human editing.

    Args:
        total_editing_time_minutes: Total time spent editing (from DOCX metadata).
        page_count: Estimated or actual number of pages in the document.

    Returns:
        Dictionary containing velocity metrics and anomaly flags.
    """
    result = {
        "editing_time_minutes": total_editing_time_minutes,
        "page_count": page_count,
        "minutes_per_page": None,
        "is_velocity_anomaly": False,
        "velocity_score": 1.0,  # 1.0 = normal, 0.0 = highly suspicious
    }

    if total_editing_time_minutes is None or page_count <= 0:
        return result

    minutes_per_page = total_editing_time_minutes / page_count
    result["minutes_per_page"] = round(minutes_per_page, 2)

    if minutes_per_page < MIN_EDITING_MINUTES_PER_PAGE:
        result["is_velocity_anomaly"] = True
        # Score drops linearly as time drops below threshold
        result["velocity_score"] = max(
            0.0, minutes_per_page / MIN_EDITING_MINUTES_PER_PAGE
        )

    return result


def analyze_author_mismatch(metadata: Dict[str, Any]) -> Dict[str, Any]:
    """Analyze author tags for mismatches.

    If the original Creator differs from the LastModifiedBy, it may indicate
    the document was templated, copied, or purchased from a third party.

    Args:
        metadata: Extracted metadata dictionary.

    Returns:
        Dictionary containing mismatch flags and scores.
    """
    result = {
        "creator": metadata.get("creator") or metadata.get("author"),
        "last_modified_by": metadata.get("last_modified_by"),
        "is_author_mismatch": False,
        "mismatch_score": 0.0,
    }

    creator = result["creator"]
    modifier = result["last_modified_by"]

    if creator and modifier and creator.lower() != modifier.lower():
        result["is_author_mismatch"] = True
        result["mismatch_score"] = AUTHOR_MISMATCH_PENALTY

    return result


def compute_provenance_risk_score(
    file_bytes: bytes, file_type: str, estimated_pages: int = 1
) -> Dict[str, Any]:
    """Compute an overall provenance risk score for a document.

    Orchestrates metadata extraction and anomaly analysis to produce
    a final risk score between 0.0 (clean) and 1.0 (highly suspicious).

    Args:
        file_bytes: Raw bytes of the document.
        file_type: File extension (e.g., 'docx', 'pdf').
        estimated_pages: Estimated number of pages for velocity analysis.

    Returns:
        Comprehensive provenance analysis report.
    """
    if file_type.lower() == "docx":
        metadata = extract_docx_metadata(file_bytes)
    elif file_type.lower() == "pdf":
        metadata = extract_pdf_metadata(file_bytes)
    else:
        logger.warning("Unsupported file type for provenance analysis: %s", file_type)
        return {"error": "Unsupported file type", "risk_score": 0.0}

    # Analyze author mismatch
    author_analysis = analyze_author_mismatch(metadata)

    # Analyze edit velocity (only applicable to DOCX usually)
    editing_time = None
    if metadata.get("total_editing_time"):
        try:
            editing_time = float(metadata["total_editing_time"])
        except ValueError:
            editing_time = None

    velocity_analysis = analyze_edit_velocity(editing_time, estimated_pages)

    # Compute overall risk score (weighted average of anomalies)
    # Author mismatch is a strong indicator, velocity is also strong
    risk_score = (author_analysis["mismatch_score"] * 0.5) + (
        (1.0 - velocity_analysis["velocity_score"]) * 0.5
    )

    return {
        "metadata": metadata,
        "author_analysis": author_analysis,
        "velocity_analysis": velocity_analysis,
        "risk_score": round(min(1.0, risk_score), 4),
        "is_suspicious": risk_score > 0.5,
    }
