"""Embedding model metadata and compatibility validation."""

from __future__ import annotations

import os
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from typing import Any

import numpy as np


VECTOR_SCHEMA_VERSION = 1
NORMALIZATION_STRATEGY = "l2"


@dataclass(frozen=True)
class EmbeddingMetadata:
    """Metadata describing the schema used to generate an embedding."""

    model_identifier: str
    model_version: str
    dimension: int
    normalization_strategy: str
    generated_at: str
    vector_schema_version: int = VECTOR_SCHEMA_VERSION

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def get_embedding_model_metadata(
    dimension: int,
    *,
    generated_at: str | None = None,
) -> EmbeddingMetadata:
    """Build metadata for embeddings generated by the active model."""
    from src.core.embedding_model import _get_model_name

    return EmbeddingMetadata(
        model_identifier=_get_model_name(),
        model_version=os.getenv(
            "SEMANTIC_PLAGIARISM_MODEL_VERSION",
            "1",
        ),
        dimension=int(dimension),
        normalization_strategy=NORMALIZATION_STRATEGY,
        generated_at=(
            generated_at
            or datetime.now(timezone.utc).replace(microsecond=0).isoformat()
        ),
    )


def get_active_embedding_metadata() -> EmbeddingMetadata:
    """Return metadata describing the currently configured model."""
    from src.core.embedding_model import get_embedding_model_info

    model_name, dimension = get_embedding_model_info()
    metadata = get_embedding_model_metadata(dimension)
    return EmbeddingMetadata(
        model_identifier=model_name,
        model_version=metadata.model_version,
        dimension=dimension,
        normalization_strategy=metadata.normalization_strategy,
        generated_at=metadata.generated_at,
        vector_schema_version=metadata.vector_schema_version,
    )


def validate_embedding_vector(
    vector: np.ndarray,
    metadata: EmbeddingMetadata,
) -> None:
    """Reject vectors that do not match their declared embedding schema."""
    if vector.ndim != 1:
        raise ValueError(
            f"Embedding vector must be 1-dimensional, got {vector.ndim} dimensions."
        )

    if vector.shape[0] != metadata.dimension:
        raise ValueError(
            "Embedding dimension mismatch: "
            f"{vector.shape[0]} != {metadata.dimension}."
        )

    if metadata.normalization_strategy != NORMALIZATION_STRATEGY:
        raise ValueError(
            "Unsupported embedding normalization strategy: "
            f"{metadata.normalization_strategy}"
        )


def ensure_compatible_metadata(
    expected: EmbeddingMetadata,
    actual: EmbeddingMetadata,
) -> None:
    """Reject embeddings generated by an incompatible schema/model."""
    fields = (
        "model_identifier",
        "model_version",
        "dimension",
        "normalization_strategy",
        "vector_schema_version",
    )

    mismatches = {
        field: (getattr(actual, field), getattr(expected, field))
        for field in fields
        if getattr(actual, field) != getattr(expected, field)
    }

    if mismatches:
        raise ValueError(
            "Incompatible embedding metadata. "
            f"Expected {expected.to_dict()}, received {actual.to_dict()}. "
            f"Mismatches: {mismatches}"
        )


def metadata_from_row(row: Any) -> EmbeddingMetadata:
    """Create metadata from a SQLite row/tuple."""
    return EmbeddingMetadata(
        model_identifier=row["model_identifier"],
        model_version=row["model_version"],
        dimension=int(row["embedding_dimension"]),
        normalization_strategy=row["normalization_strategy"],
        generated_at=row["embedding_generated_at"],
        vector_schema_version=int(row["vector_schema_version"]),
    )